INSERT INTO alunos VALUES (NULL, 'Ana Carla dos Santos', 'ana@gmail.com', 9),
                          (NULL, 'Anderson Pereira Cordeiro Honorato', 'anderson@gmail.com', 9),
                          (NULL, 'André Alisson Monteiro Lucena', 'andre@gmail.com', 9),
                          (NULL, 'Antônio Marcos de Sousa Paulo', 'antonio@gmail.com', 9),
                          (NULL, 'Bianca Rocha Araújo', 'bianca@gmail.com', 9),
                          (NULL, 'Brayan Kalil Pereira de Queiroz', 'brayan@gmail.com', 9),
                          (NULL, 'Brena dos Santos Araújo', 'brena@gmail.com', 9),
                          (NULL, 'Clarice Rodrigues Dantas', 'clarice@gmail.com', 9),
                          (NULL, 'Clarissa Sousa Gomes', 'clarissa@gmail.com', 9),
                          (NULL, 'Dyná Heloize Lima de Sousa', 'dyna@gmail.com', 9),
                          (NULL, 'Emília Ketly Medeiros Pereira', 'emilia@gmail.com', 9),
                          (NULL, 'Érika da Guia Lucena Bibiano', 'erika@gmail.com', 9),
                          (NULL, 'Estefany Linhares Monteiro de Araujo', 'estefany@gmail.com', 9),
                          (NULL, 'Felipe Monteiro da Silva', 'felipe@gmail.com', 9),
                          (NULL, 'Gabriel Kleber da Silva Batista', 'gabriel@gmail.com', 9),
                          (NULL, 'Geovanna dos Santos Medeiros', 'geovanna@gmail.com', 9),
                          (NULL, 'Guilherme da Silva Pereira', 'gui@gmail.com', 9),
                          (NULL, 'Guilherme Santos de Medeiros', 'ipueira@gmail.com', 9),
                          (NULL, 'Helena Dantas Mariano', 'helena@gmail.com', 9),
                          (NULL, 'Jessé Leandro Dias', 'jesse@gmail.com', 9),
                          (NULL, 'Jonas Ramos Tomaz', 'jonas@gmail.com', 9),
                          (NULL, 'José Etelvino de Medeiros', 'etelvino@gmail.com', 9),
                          (NULL, 'José Henrique Soares Rodrigues Morais', 'henrique@gmail.com', 9),
                          (NULL, 'José Samuel Silva Lima', 'samuel@gmail.com', 9),
                          (NULL, 'Joyce Pedrosa dos Santos', 'joyce@gmail.com', 9),
                          (NULL, 'Kaio Monteiro de Souza', 'kaio@gmail.com', 9),
                          (NULL, 'Kaue Kennedy Araujo Vicente', 'kaue@gmail.com', 9),
                          (NULL, 'Kayque Ferreira de Albuquerque', 'kayque@gmail.com', 9),
                          (NULL, 'Laianny de Freitas Lucena', 'laianny@gmail.com', 9),
                          (NULL, 'Leislane Simplicio Rodrigues', 'leislane@gmail.com', 9),
                          (NULL, 'Letícia Skarlet de Medeiros Lucena', 'leticia@gmail.com', 9),                          
                          (NULL, 'Maria Cecília de Morais Pereira Soares', 'cecilia@gmail.com', 9),
                          (NULL, 'Maria Clara Lima de Sousa', 'clara@gmail.com', 9),
                          (NULL, 'Maria Isabel Angelo Batista de Souza', 'isabel@gmail.com', 9),
                          (NULL, 'Mariana Simões de Souza Silva', 'mariana@gmail.com', 9),
                          (NULL, 'Maria Rita Araújo Felix', 'rita@gmail.com', 9),
                          (NULL, 'Mateus Soares da Rocha Cordeiro', 'mateus@gmail.com', 9),
                          (NULL, 'Nafanael Pereira Alves', 'nafan@gmail.com', 9),
                          (NULL, 'Nícolas Nóbrega Dantas', 'nicolas@gmail.com', 9),
                          (NULL, 'Paulo Andre Gomes Fernandes', 'paulo@gmail.com', 9),
                          (NULL, 'Vitoria Linhares Sales Mota', 'vitoria@gmail.com', 9),
                          (NULL, 'Vívia Lopes Gomes', 'vivia@gmail.com', 9),
                          (NULL, 'Yarlei Ryan Oliveira Gois', 'yarlei@gmail.com', 9)